### ISSUE TITLE
[Feature Request] Add support for Redragon K587 TKL

### ISSUE THREAD

**Issue by ng1nx02** [SonixQMK/qmk_firmware#104]
## Feature Request Type

- [X] Core functionality
- [X] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description
 I'd like full support for Redragon K587 as Evision software is sh**.

**Comment by lucas-strummer** [comment]
This feature would be awesome
