### ISSUE TITLE
[Feature Request] Add support for Redragon K586 Brahma

### ISSUE THREAD

**Issue by xlen** [SonixQMK/qmk_firmware#105]
- [ ] Core functionality (including media functions/keys)
- [ ] G key macro proper setup support
- [ ] M key profile setup (optional, but welcome)
- [ ] Alteration (enhancements/optimizations) of existing features
## Description
I'd like to see a full and in some ways improved support for Redragon Brahma, the stock software only allows to add something on G keys through the keyboard itself, not by windows software, that's generally the main issue I have with stock firmware, it's a bit clunky, but otherwise functional, cooler RGB features might be welcome, but IMHO, not a priority in any way, personally, I'm fine with 1-2 colors addressable through the keyboard.
Anyways in hopes that someone picks it up,
Sincerely Xlen.

**Comment by ERNAZAR02** [comment]
Add support for Redragon K586 Brahma (non pro)
