### ISSUE TITLE
[Bug] RGB matrix not working in columns with shared PWM

### ISSUE THREAD

**Issue by Jpe230** [SonixQMK/qmk_firmware#124]
## Describe the Bug

Declaring an RGB matrix with columns pins with shared PWM results in the A pins being omitted from the RGB matrix.

Example from my particular board (SN32F248B) : 
`#define LED_MATRIX_COL_PINS { A8, A9, C0, C1 (...rest omitted) } `

Being that A8 and C0 shares PWM08 (A and B respectively) and A9 and C1 shares PWM09 (A and B respectively)

**Comment by guilleortas** [comment]
Hi there, were you able to solve this? I'm having the same issue on my Calibur V2 TE ISO

**Comment by dexter93** [comment]
The solution for this is software pwm. The CT16 config can't be refreshed unless a new pwm cycle is started ( hardware limitation), so even swapping the pin control on the fly will not work

**Comment by dexter93** [comment]
check out https://github.com/SonixQMK/qmk_firmware/pull/295

**Comment by dexter93** [comment]
An even faster and more reliable solution lives in https://github.com/SonixQMK/qmk_firmware/pull/344. Swap the PWM direction around. Scan times will be slower, but heaps faster than software PWM
