### ISSUE TITLE
[Feature Request] Add support for SPC Gear GK630

### ISSUE THREAD

**Issue by ppkt** [SonixQMK/qmk_firmware#127]
## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

Recently I bought a SPC Gear GK630 and I'm wondering how much work is needed to use this firmware with this keyboard. I see that other models from the same vendor are already supported (GK530/GK540 but they're using a slightly different MCU).

I have some basic knowledge about QMK and electronics and I'd like to add support for this keyboard but I'm not sure where to start :)

**Comment by dexter93** [comment]
Keyboard additions usually happen by taking apart the keyboard and spending some time with a multimeter. Start with some basic reverse engineering like [this](https://github.com/dexter93/keychron-k4)

**Comment by ppkt** [comment]
Wonderful, many thanks!
