### ISSUE TITLE
[Feature Request] Aukey KM-G12

### ISSUE THREAD

**Issue by maxill1** [SonixQMK/qmk_firmware#15]
This is what I can provide for this keyboard:

lsusb result:
`ID 0c45:8006 Microdia Dual Mode Camera (8006 VGA)`

Chip: **HFD2201KBA**
<details>

![IMG20220105105737](https://user-images.githubusercontent.com/367042/148203001-c8a7f607-e0a9-463f-bf41-85bc7669be11.jpg)

</details>

Board: **GK4105M-RGB-HFD** (switches are soldered directly on board so i can't take pictures of the front board right now)
<details>

![IMG20220105105717](https://user-images.githubusercontent.com/367042/148203008-eb9da835-9787-45a7-a01c-3eb2b00155b2.jpg)

![IMG20220105114530](https://user-images.githubusercontent.com/367042/148205212-22376527-2c1c-4d8e-b532-b0db3c4ae327.jpg)

</details>

Brand: **[Aukey KM-G12](https://it.aukey.com/products/km-g12-mechanical-keyboard-blue-switches)** (according to [this OpenRGB](https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues/1992) issue it may to be an OEM clone of "Sandberg Firestorm Mech Keyboard")
Layout: 100% 
<details>

![IMG20220105105822](https://user-images.githubusercontent.com/367042/148203016-a3c9e77c-6f19-4b3a-9bf4-92fad776e14d.jpg)
![KM-G121_600x](https://user-images.githubusercontent.com/367042/148203110-6d4c1c7c-27f3-4b18-bee2-fe32f9ab2904.jpg)

</details>

You can enter bootloader by connecting boot pin to a ground source.

![InkedIMG20220105153909](https://user-images.githubusercontent.com/367042/148236513-3296e98d-4c1d-43dc-bdb5-565aa1554ddd.jpg)

In bootloader vid and pid is: 0c45:7040.

**Comment by Krutonium** [comment]
Your best bet is to tear the keyboard down and take a picture of the chip that's running the show, that will tell us a lot.

**Comment by maxill1** [comment]
Edit:

updated main post.

Just for fun I flashed a couple of Redragon K556 firmwares (redragon_k556_default.bin from [61ff878](https://github.com/SonixQMK/qmk_firmware/suites/4826547721/artifacts/136320784) and [b7c83a4](https://github.com/SonixQMK/qmk_firmware/suites/4390942934/artifacts/115740232) ). In openrgb branch leds are all up spinning in a rainbow pattern. Keys are all ko in both firmwares.

I'm going to read the docs to see what I can do to debug and support the keyboard. Any help will be appreciated.
