### ISSUE TITLE
[Feature Request] Make compile check fail, when build is broken

### ISSUE THREAD

**Issue by IsaacDynamo** [SonixQMK/qmk_firmware#155]
Currently the 'Compile Firmware' check will not fail if there are boards that don't build. 
So it is possible to merge code that doesn't even compile. 

It would be nice if the check gave real feedback if a PR is save to merge.

For example https://github.com/SonixQMK/qmk_firmware/pull/154 would have been caught a month earlier.

## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

**Comment by jath03** [comment]
This could probably be added.  The compile firmware was just intended to be a convenience so that people don't have to set up a local build environment, but I could make it fail if a keyboard doesn't compile.
