### ISSUE TITLE
[Feature Request] Support Caps lock LED on Keychron K3

### ISSUE THREAD

**Issue by seppestas** [SonixQMK/qmk_firmware#177]
The red Caps lock indicator LED does not work on the Keychron K3 (v1, Optical RGB). Instead of turning on/off when capslock is pressed, it is always dimly on.

## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

The build for the RGB Keychron K3 with optical switches works if the `OPTICAL_MATRIX` macro is defined, but the Caps lock indicator feature does not seem to be working. The LED is expected to turn on if Caps lock is enabled and off if Caps lock is disabled. Instead,  the LED is always in a dim-on state, which could indicate a floating gate condition.

PCB version: Ver 1.4/20201030

Built from 03c781d3ca5b024ec3c21d85ad5f323aff70d842 with arm-none-eabi-gcc version 10.1.0 on Windows 10 with QMK MSYS 1.5.2.

**Comment by dexter93** [comment]
Keychron K3 doesn't have declared GPIO for Caps Lock. Please identify what pin that LED is hooked up to on the MCU so that it can be properly handled.
