### ISSUE TITLE
[Bug] FFC61 only works when using pre-compiled bin file

### ISSUE THREAD

**Issue by junopaulo-deguzman** [SonixQMK/qmk_firmware#178]
Compiling using the instructions does compile successfully but the result is glitchy(double keypresses) 

## System Information

 - Keyboard:  
   - Revision (if applicable):  
 - Operating system:
 - AVR GCC version: 

 - ARM GCC version: 

 - QMK Firmware version:

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by dexter93** [comment]
This should be sorted in latest trees. If not, please adjust the debounce value
