### ISSUE TITLE
[Feature Request] Support LED flush for rgb_matrix_indicators_user function

### ISSUE THREAD

**Issue by HorrorTroll** [SonixQMK/qmk_firmware#188]
## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description
After we have many changes of PWM, but we still missing an LED flush function. Since most keyboard doesn't have LED indicator for Capslock. So rgb_matrix_indicators_user on keymap really helped for that, but we missing LED flush so it make a flickering led color when toggle it.

**Comment by dexter93** [comment]
done with https://github.com/SonixQMK/qmk_firmware/commit/00922a8aefc222ab2864bf18a4f3c035977e19de
