### ISSUE TITLE
[Bug] Keychron K7 with AMD CPU is unresponsiable

### ISSUE THREAD

**Issue by yuanqiuye** [SonixQMK/qmk_firmware#246]
## Describe the Bug

Flashed QMK onto K7 with 0x00 offset, after flashed everything seems OK, but when I plug out and plug in again, my K7 become unresponsiable for computer, only backlight can work. (Only on AMD CPUs, Intel's can work normally)

## System Information

 - Keyboard:  Keychron K7 RGB optical
 - Operating system: Windows 11
 - AVR GCC version: 8.3.0
 - ARM GCC version: 11.2.0
 - QMK Firmware version: 0.7.101

## Additional Context
In device manager:
- After flashed:
<img width="114" alt="image" src="https://user-images.githubusercontent.com/18190066/156620526-95d8059f-adeb-4209-92b9-de3da80b0350.png">

- plug in and plug out (unresponsiable):
<img width="86" alt="image" src="https://user-images.githubusercontent.com/18190066/156620676-42a13628-a883-4428-86c7-973339b3c655.png">
(Standard PS/2 keyboard)

**Comment by dexter93** [comment]
Issue has been resolved with latest USB LLD updates. History log [here](https://github.com/SonixQMK/ChibiOS-Contrib/commits/sn32_develop/os/hal/ports/SN32/LLD/SN32F2xx/USB)
