### ISSUE TITLE
State of SonixQMK? Support needed? 

### ISSUE THREAD

**Issue by cmorty** [SonixQMK/qmk_firmware#261]
Hey, what is the state of this Project? The last activity is 1,5 months ago and there are 37 MRs piling up. I know this is solely a fun project, but is there any way it can be supported, to free resources or improve motivation? I can offer review and some development resources, but I need something, too (too many projects that got abandoned despite people putting efforts into it). ;)  Maybe a roadmap?

**Comment by dexter93** [comment]
Too few devs and limited time. Cleanup also needed in places since we're trying to get things merged to upstream repos, so the trees are a mess. Timeline is a bit vague now, but there's an order of things to be done. Join up on discord to discuss it further if you want to help :)

**Comment by saidnamyzO** [comment]
I would give my life to know how to colaborate with the bluetooth development. It was great using the firmware in my K2 V2 keyboard but went back to stock after seeing because I really need to go wireless every now and then : (

**Comment by crazyquark** [comment]
how can I help? I have a GMMK TKL rev2 for which I compiled a firmware from this repo.
