### ISSUE TITLE
Keychron K7 Gateron RGB 

### ISSUE THREAD

**Issue by daltona** [SonixQMK/qmk_firmware#267]
Current sn32_master, despite of supporting the keychron K7, is not working on my brand new keyboard. 

## System Information

 - Keyboard:  
   Keychron K7 Gateron mechanical (not optical) (K004-3-RGB 48RGB V1.1 20211125)

## Additional Context

After probin the key matrix and the led matrix pins to microcontroller, I managed to start using it as a keyboard.

What should I do to properly add this code to the repository ( my understanding i that current changes should only apply to the non-optical version of the K7 keyboard)

pr #268 has the changes that make my device work as a keyboard: 

anywone having same issue ?

**Comment by dexter93** [comment]
The initial bringup was on a optical k7 rgb and confirmed working. Maybe there is a pcb revision. Will update when things become a bit clearer

**Comment by dexter93** [comment]
K7 RGB hotswap mechanical got hit by silicon shortage, hence the 247b chip inside. Soldered was not

the rest of the K7 RGB variants are using the 248b chip, so things related to this PR should be moved accordingly to a `hotswap` variant
