### ISSUE TITLE
[Bug] GMMK TKL randomly locks up or spams bbbbbb

### ISSUE THREAD

**Issue by tgharib** [SonixQMK/qmk_firmware#271]
## Describe the Bug

If you press a key combination with 3 or 4 keys hold down, the keyboard either locks up or spams bbbbb or 3b3b3b3b. The bug is not 100% consistently reproducible. The most reliable method I've found to reproduce is to simply mash a lot of butons on the keyboard rapidly.

## System Information

 - Keyboard:  gmmk (v1) tkl rev3 with CPU VS11K13A
 - Operating system: Reproduced on both archlinux and windows
 - AVR GCC version: 12.1.0
 - ARM GCC version: 12.1.0
 - QMK Firmware version: 0.7.101 (on working sn32 branch)
 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

## Additional Context

If you use `sn32` branch instead of `sn32_master` branch, the bug goes away.

**Comment by dexter93** [comment]
Bug traces back to timer. Should be fixed with https://github.com/SonixQMK/qmk_firmware/commit/238e200904f2ccea5de10bddb70ac07845e5830d

**Comment by waht** [comment]
Can confirm that my gmmk rev2 full size which was previously also spamming is now working properly. Thank you very much!

**Comment by tgharib** [comment]
I can confirm that I can no longer reproduce with `sn32_master`. Thanks!
