### ISSUE TITLE
Add function Caps Word

### ISSUE THREAD

**Issue by agdral** [SonixQMK/qmk_firmware#281]
## Feature Request Type

- [x] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

In my opinion, I think it is a very useful function. but I don't know why it's not implemented in this fork yet

more information about the function [here](https://docs.qmk.fm/#/feature_caps_word)

**Comment by tbowmo** [comment]
That feature was added roughly 6 months ago in upstream, so probably after we did the latest update to this projects develop branch.

**Comment by dexter93** [comment]
Deviating from upstream QMK functionality is not in the scope of this project. When we sync again to the latest snapshot, all new QMK features will be included.
