### ISSUE TITLE
Keychron K3 Version 2: Document if is supported

### ISSUE THREAD

**Issue by nahuel** [SonixQMK/qmk_firmware#283]
The documentation in the "Compatible Keyboards" section states the Keychron K3 is supported, but doesn't specify if the K3 Version 2 is also supported. If is already supported please add it to the documentation.

**Comment by nahuel** [comment]
Note: As I saw here, the K3V2 seems to be compatible: https://seyahdoo.com/blog/qmk-on-keychron-k3v2/  but only the RGB version

**Comment by p-hash** [comment]
For future: it is supported. https://github.com/SonixQMK/qmk_firmware/tree/sn32/keyboards/keychron/k3/rgb
