### ISSUE TITLE
How can I download firmware?

### ISSUE THREAD

**Issue by cdytoby** [SonixQMK/qmk_firmware#326]
I come from this tutorial: https://github.com/CanUnesi/QMK-on-K6#8-optional-using-via
It says I need to download firmware from CI actions. However, I can't download any, because all build artifacts are out of date.

Is there any firmware download archive I can check so that I can download and flash firmware myself?

I need Keychron K6 Firmware with VIA support.

**Comment by ludalex** [comment]
Up!
