### ISSUE TITLE
too large to run in SRAM

### ISSUE THREAD

**Issue by SSSLiurong** [SonixQMK/qmk_firmware#331]
It seems that my program is too large to run in SRAM, but I didn't add any other extra function except for basic input function. why?
I use SN32f268 as my mcu. 
![80GFT40KZ7UZKMGKD6L](https://github.com/SonixQMK/qmk_firmware/assets/129812275/9438e325-51c2-494e-afd6-6bbc10d411d0)

**Comment by dexter93** [comment]
See https://github.com/SonixQMK/qmk_firmware/blob/sn32_develop/keyboards/handwired/onekey/sn32f260/rules.mk

**Comment by fightforlife** [comment]
I am also using 268f with sonixqmk and a slimmed RGB driver (no double buffer, no idle thread, minimized stack,..)
See here for reference
https://github.com/fightforlife/qmk_firmware/tree/sn32_develop_k66v1/keyboards/womier/k66
