### ISSUE TITLE
Where are the precompiled binaries for C1 that the appropriate page refers to?

### ISSUE THREAD

**Issue by michaelliberman** [SonixQMK/qmk_firmware#354]
### Issue Description

This page:
https://github.com/SonixQMK/qmk_firmware/tree/sn32/keyboards/keychron/c1/white
Refers to precompiled jumploader and firmware binaries under Github actions in the project.
Where are they?
I don't see those actions, neither I can find those prebuild binaries anywhere.
Is setting up a local environment and compiling from source, the only option?

**Comment by dexter93** [comment]
Hi, prebuilts proved to be problematic in the long run. They were initially set up to aid development, but too many people thought they were stable releases. We have disabled the CI used to generate them since. Building from source is recommended and encouraged.

**Comment by michaelliberman** [comment]
Yeah, I ended up setting up a dev environment and building it myself, from the master-stable branch.
It is pretty old though, looks like the code hasn't been touched since 2021?
And its not 100% stable.
It does work well most of the time, but sometimes (I haven't found the exact culprit, but seems to be related to using FN modifier), it drops off and stops responding.
When it happens, the light turns off.
In those cases, I just unplug and plug back in.
I did compile the VIA version.
Can I open an issue about that, or is it a known problem for this keyboard?

**Comment by dexter93** [comment]
> Yeah, I ended up setting up a dev environment and building it myself, from the master-stable branch. It is pretty old though, looks like the code hasn't been touched since 2021? And its not 100% stable. It does work well most of the time, but sometimes (I haven't found the exact culprit, but seems to be related to using FN modifier), it drops off and stops responding. When it happens, the light turns off. In those cases, I just unplug and plug back in. I did compile the VIA version. Can I open an issue about that, or is it a known problem for this keyboard?

Platform support has gone over a major overhaul for stability and speed improvements, on the latest active branch `sn32_develop`. Other branches in the repository should be treated as archived and thus, stale. We do not track issues on those. Some features might be missing ( namely, the single color LED shared driver) and keyboards ( unmaintained keyboards haven't been brought up in the current active branch). Feel free to port it over if missing and open a PR

**Comment by michaelliberman** [comment]
Is there any tutorial on how to undertake such a project?
Namely, to port this keyboard (which is no longer included) back into active branch?

**Comment by dexter93** [comment]
See a similar keyboard PR, like https://github.com/SonixQMK/qmk_firmware/pull/358
