### ISSUE TITLE
[Feature Request] Redragon k585 support 

### ISSUE THREAD

**Issue by SenorSmartyPants** [SonixQMK/qmk_firmware#378]
### Feature Request Type

- [ ] Core functionality
- [X] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Would it be possible to support the Redragon k585 one hand keyboard?

Thank you

**Comment by itaranto** [comment]
I was also interested in this keyboard. How hard is to support a new keyboard like this?

It seems there's some information about the K585 here: https://github.com/SonixQMK/Mechanical-Keyboard-Database?tab=readme-ov-file#one-handed-layout

And also there seems to be support already for a couple of Royal Kluge keyboards which apparently have the same MCU.
