### ISSUE TITLE
[Bug] Invalid return_code: 2816

### ISSUE THREAD

**Issue by codebasel** [SonixQMK/qmk_firmware#388]
### Describe the Bug

when i try to compile the firmware for the k552-1 i get an error that says: Invalid return_code: 2816

### Keyboard Used

redragon/k552/rev1 

### Operating System

win11

### qmk doctor Output

```text
QMK Doctor is checking your environment.
Ψ CLI version: 1.1.5
Ψ QMK home: C:/Users/Admin/qmk_firmware
Ψ Detected Windows 10 (10.0.22631).
Ψ Git branch: sn32_master_stable
☒ Can't find arm-none-eabi-gcc in your path.
☒ Can't find avr-gcc in your path.
☒ Can't find avrdude in your path.
☒ Can't find dfu-programmer in your path.
☒ Can't find dfu-util in your path.
```

### Is AutoHotKey / Karabiner installed

- [X] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Other keyboard-related software installed

the k552-1 software

**Comment by dexter93** [comment]
MSYS issue affecting older branches. Fix: remove unwanted keyboard directories locally before building.
