### ISSUE TITLE
[Bug] Unable to build Keychron K8

### ISSUE THREAD

**Issue by creeve4** [SonixQMK/qmk_firmware#399]
### Describe the Bug

Using the default make command `make keychron/k8/rgb/ansi:ansi` produces this output:

[creev@DESKTOP-CC9E002 SonixQMK-dev]$ make keychron/k8/rgb/ansi:ansi
QMK Firmware 0.25.7
☒ Not including data from file: keyboards/keychron/k8/rgb/info.json
☒       usb: Additional properties are not allowed ('wait_for' was unexpected)
☒ 'matrix_size'
Traceback (most recent call last):
  File "C:/QMK_MSYS/mingw64/lib/python3.10/site-packages/milc/milc.py", line 528, in __call__
    return self.__call__()
  File "C:/QMK_MSYS/mingw64/lib/python3.10/site-packages/milc/milc.py", line 533, in __call__
    return self._subcommand(self)
  File "T:/QMK/SonixQMK-dev/lib/python/qmk/decorators.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "T:/QMK/SonixQMK-dev/lib/python/qmk/cli/list/layouts.py", line 21, in list_layouts
    info_data = info_json(cli.config.list_layouts.keyboard)
  File "T:/QMK/SonixQMK-dev/lib/python/qmk/info.py", line 255, in info_json
    info_data = _extract_led_config(info_data, str(keyboard))
  File "T:/QMK/SonixQMK-dev/lib/python/qmk/info.py", line 757, in _extract_led_config
    cols = info_data['matrix_size']['cols']
KeyError: 'matrix_size'
Making keychron/k8/rgb/ansi with keymap ansi

☒ Not including data from file: keyboards/keychron/k8/rgb/info.json
☒       usb: Additional properties are not allowed ('wait_for' was unexpected)
☒ 'matrix_size'
Traceback (most recent call last):
  File "C:/QMK_MSYS/mingw64/lib/python3.10/site-packages/milc/milc.py", line 528, in __call__
    return self.__call__()
  File "C:/QMK_MSYS/mingw64/lib/python3.10/site-packages/milc/milc.py", line 533, in __call__
    return self._subcommand(self)
  File "T:/QMK/SonixQMK-dev/lib/python/qmk/cli/generate/rules_mk.py", line 65, in generate_rules_mk
    kb_info_json = dotty(info_json(cli.args.keyboard))
  File "T:/QMK/SonixQMK-dev/lib/python/qmk/info.py", line 255, in info_json
    info_data = _extract_led_config(info_data, str(keyboard))
  File "T:/QMK/SonixQMK-dev/lib/python/qmk/info.py", line 757, in _extract_led_config
    cols = info_data['matrix_size']['cols']
KeyError: 'matrix_size'

 *                                                                                                     [ERRORS]

builddefs/build_keyboard.mk:226: *** Platform not defined.  Stop.
Make finished with errors
make: *** [Makefile:415: keychron/k8/rgb/ansi:ansi] Error 1

### Keyboard Used

keychron/k8

### Operating System

Windows 10

### qmk doctor Output

```text
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.1
Ψ QMK home: T:/QMK/SonixQMK-dev
Ψ Detected Windows 10 (10.0.19045).
Ψ QMK MSYS version: 1.7.2
Ψ Userspace enabled: False
Ψ Git branch: sn32_develop
Ψ Repo version: 0.25.7
⚠ Git has unstashed/uncommitted changes.
Ψ - Latest sn32_develop: 2024-06-11 23:23:44 +0300 (6c4eb11290) -- designedbygg: move encoder_map feature to keymaps
Ψ - Latest upstream/master: None
Ψ - Latest upstream/develop: None
Ψ - Common ancestor with upstream/master: None
Ψ - Common ancestor with upstream/develop: None
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 10.1.0
Ψ Found avr-gcc version 8.5.0
Ψ Found avrdude version 7.0
Ψ Found dfu-programmer version 0.7.2
Ψ Found dfu-util version 0.11
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2024-02-17 19:20:06 +0000 --  (be44b3305)
Ψ - lib/chibios-contrib: 2024-06-11 20:21:49 +0200 --  (56216250fb)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2023-02-12 20:19:37 +0100 --  (a3398d8)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ QMK is ready to go, but minor problems were found
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by dexter93** [comment]
Bug fixed with 5f3234e83ee76bcc68401c8916a0184295477a4e
