### ISSUE TITLE
[Bug] QMK failiure on Python 3.12. for `sn32_stable` due to https://github.com/qmk/qmk_firmware/pull/22562

### ISSUE THREAD

**Issue by Swiftb0y** [SonixQMK/qmk_firmware#402]
### Describe the Bug

Since https://github.com/qmk/qmk_firmware/pull/22562 has not been included, using this fork on newer python versions fails. Please merge an recently up-to-date upstream commit into `sn32_stable` if possible to fix this. Thank you.

### Keyboard Used

N.A.

### Link to product page (if applicable)

N.A.

### Operating System

Fedora 40

### qmk doctor Output

```text
N.A.
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Other keyboard-related software installed

None

**Comment by dexter93** [comment]
Closing since `sn32_stable` is an inactive branch left here for archival purposes. Please move to `sn32_develop`

**Comment by Swiftb0y** [comment]
Thanks for the clarification. Will do.

**Comment by dexter93** [comment]
Bug fixed with ca5b5ee0f6098f7920ed31a40b5fb1b4bd673515

**Comment by Swiftb0y** [comment]
Thanks. Had reverted back to python3.9 in the meantime.
