### ISSUE TITLE
[Bug] ISO K552 bugs found

### ISSUE THREAD

**Issue by daniarla** [SonixQMK/qmk_firmware#70]
## Describe the Bug

I flashed the latest firmware available and I found various bugs. This is a documentations of them.

<del>1. The NKRO no longer works and you only get 5-kro.
<del>2. The alt-gr does not work.<del>
3. It does not work with via (But i suppose that that is deactivated on purpose as is a specific build flag)
<del>4. The scroll lock led does not work on Linux (more in the next comment). Tested in Fedora, Arch (KDE) and Linux Mint.<del>

## System Information

 - Keyboard:  ISO K552
   - Revision (if applicable):   rev 2
 - Operating system: Arch Linux /  Windows 
 - QMK Firmware version: Last compiled firmware from github actions 
 - Any keyboard related software installed? 
 No
## Additional Context

My model is the ISO version and it could cause key-map related bugs.

All the issues have been fixed!

**Comment by daniarla** [comment]
<del>In relation to the scroll led not working:
I later tested the stock firmware that can be found in the mechanical-keyboard-database and it had the same result.
I don't know if my keyboard had that same firmware as I didn't dump it myself but I would suppose so.
Seems like Linux in particular somehow register the key-press but hijacks it not allowing the led to turn on.
The led works even in the grub as I noticed that before fully booting the led works.<del>

<del>In a keyboard tester app the key-press goes through and it works like it should, the only problem is the led.<del>

**Comment by CalcProgrammer1** [comment]
Indicator LEDs are set by the OS, they are not automatically toggled on the keyboard side.  If it works in GRUB but not in Linux, the firmware is fine.   Something in Linux is preventing the indicator from toggling on.

**Comment by daniarla** [comment]
I suspected that but I wanted to get a 2nd opinion on it just to be sure!

I edited my previous comments reflect only the 3 first problems!

**Comment by daniarla** [comment]
I corrected my first message because the key not working was the alt-gr, not the alt as my keycap set has no alt-gr keycap and I used and alt.
This is a ISO only key.

**Comment by manuhank** [comment]
@daniarla alt_gr its working fine for me. would you test using my branch on this PR?https://github.com/SonixQMK/qmk_firmware/pull/264
If you don't  know how to compile, pinkg me and I can send you the bin.

**Comment by daniarla** [comment]
@manuhank alt_gr was also working fine for me, it was a problem with the software that I used for testing.
Btw, do you have N-key rollover working? I remember  that being an issue with qmk.

**Comment by manuhank** [comment]
@daniarla using this web https://www.mechanical-keyboard.org/, I can press up to 6 letters/numbers. It also adds up the modifiers key.
Not sure if that NKRO, 6KRO, or what.

**Comment by daniarla** [comment]
@manuhank Yeah with qmk you get then 6kro, but with the original firmware you get NKey. I'm not sure why.
In that web I managed to get like 28 different keys detected.

**Comment by manuhank** [comment]
@daniarla Have you tried adding:

/* Enable NKRO - Up to 248 keys at the same time. */
#define FORCE_NKRO

to the config?

**Comment by daniarla** [comment]
@manuhank Last time I compiled qmk was last year, and I don't remember (don't think so). 
I don't have much free time in the upcoming days, so I can not test it this week. Could you try it and let me know ?

**Comment by manuhank** [comment]
@daniarla: Just tested and seems working fine, even on the bios. here you have a build 
with NKRO enabled
DEFAULT: https://1drv.ms/u/s!AvQM1RvGBOHEicNE50z6i7gYD9CDQA?e=iRveNg
ISO: https://1drv.ms/u/s!AvQM1RvGBOHEicNGTLQ08frBBnGLiQ?e=HnTdA0
Enjoy

**Comment by manuhank** [comment]
If you too confirm this works correctly, I would ask @CalcProgrammer1  what's the policy over this. should I rise a PR for this to be the default behavior, or it would be considered a personal config, and thus, not of interest for the repo. In that last case, this issue should be closed.

**Comment by daniarla** [comment]
@manuhank Im sorry for the delayed response but I had exams and a lot of things to work on.
I just tried your firmware and I can confirm that NKRO works perfectly!
