### ISSUE TITLE
[Bug] on some systems: orgb + shared ep + force nkro + media keys = kb unresponsive after restarts

### ISSUE THREAD

**Issue by stdvar** [SonixQMK/qmk_firmware#78]

**Comment by stdvar** [comment]
Check USB lld driver + shared ep code to identify potential bug

**Comment by vjdato21** [comment]
### Initial findings

**Shared EP + NKRO + FORCED NKRO** = Responsive keyboard even with RGB programs hooked via direct mode. Keyboard though doesn't register keystrokes when it was plugged in before the PC boots. (Temporary workaround: Reconnect the keyboard USB cable to the PC)

**NKRO + FORCED NKRO** = Recognizes more than 6 keystrokes but, keystrokes do not register properly when used with RGB programs hooked via direct mode. 

**NKRO only** = only recognizes 6 keystrokes max, it can also have performance problems depending on your RGB settings/program.

**Comment by vjdato21** [comment]
### Possible cause identified.
Keyboard may not be detected if the endpoints are shared in some BIOSes.

**Comment by vjdato21** [comment]
https://beta.docs.qmk.fm/developing-qmk/qmk-reference/config_options

> ### Possible cause identified.
> Keyboard may not be detected if the endpoints are shared in some BIOSes.
