### ISSUE TITLE
[Bug] LED Status on C1 Hotswap RGB

### ISSUE THREAD

**Issue by vjdato21** [SonixQMK/qmk_firmware#86]
## Describe the Bug

- Toggling num lock affects the **Windows Mode** status LED.
- If the keyboard was set to **Mac Mode** and the num lock was toggled, the **Mac Mode** status LED turns off **Windows Mode** turns on instead.
- **Mac Mode** is now set as scroll lock status LED. (Tested it by pressing scroll lock, this issue wasn't present before the unification of matrix.)

## System Information

 - Keyboard:  Keychron C1 Hotswap RGB
   - Revision (if applicable):  
 - Operating system: Windows 10 21H1
 - AVR GCC version: 8.4.0

 - ARM GCC version: 10.1.0

 - QMK Firmware version: 0.7.101

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [x] Other: OpenRGB, Artemis

## Additional Context
[Demonstration](https://streamable.com/na9g4b)

**Comment by IsaacDynamo** [comment]
Had similar issues with my C1 White and fixed it. Maybe you can do something similar.
https://github.com/IsaacDynamo/qmk_firmware/blob/keychron_c1_white/keyboards/keychron/c1_white/keymaps/default/keymap.c

**Comment by vjdato21** [comment]
A fix is coming...
